  jenkins-slave-java:
    container_name: jenkins-slave-java
    restart: always
    image: avsdeveng/jenkins-slave:0.2.0
    networks:
      - adopnetwork
    privileged: true
    environment:
      - "constraint:tier==jenkins"
      - "SLAVE_LABELS=aws ldap java8 ansible terraform packer docker"
      - "SLAVE_NAME=SLAVE_ANSIBLE"
      - "SWARM_PASSWORD=${PASSWORD_JENKINS}"
      - "SLAVE_EXECUTORS=2"
      - "INITIAL_ADMIN_USER=${INITIAL_ADMIN_USER}"
      - "INITIAL_ADMIN_PASSWORD=${INITIAL_ADMIN_PASSWORD_PLAIN}"