infra-toolkit-slave:
  image: avsdeveng/infra-toolkit-slave:latest
  restart: always
  privileged: true
  environment:
    SLAVE_MODE: "exclusive"
    SLAVE_NAME: "infra"
    SLAVE_LABELS: "infra"
    SWARM_MASTER: "http://jenkins:8080/jenkins/"
    NO_AUTH: "true"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock